---
- name: List SSH keys available in account
  command: >
    ibmcloud is keys --json
  register: r_ssh_keys

- name: Create SSH key if it does not exist
  when: (r_ssh_keys.stdout | from_json) | json_query(ssh_key_query) | length == 0
  command: >-
    ibmcloud is keyc {{ guid }}-key "{{ infra_ibm_ssh_key_pubssh_key }}"
    --json --resource-group-id {{ resource_group_id }}
  vars:
    ssh_key_query: >
      [?name=='{{ guid }}-key']

# Saving this for now...
# Don't think we need this...this is method for classic infra, not VPC infra
# - name: List ssh-keys available
# # Should be changed to Ansible module
#   command: >-
#     ibmcloud sl security sshkey-list--output json
#   register: r_sshkey_list

# - name: Block to create sshkey file if it does not exist
#   block:
#   when: GUID not in r_sshkey_list.stdout
    # - set_fact:
    #     pub_ssh_key: "{{ infra-ibm-ssh-key-pubssh-file }}"

    # - name: Create pubssh file
    #   file:
    #     contents: "{{ infra-ibm-ssh-key-pubssh-key  }}"
    #     dest: "{{ pub_ssh_key }}"

    # - name: Upload the ssh-keys
    #   command: >-
    #     ibmcloud sl security sshkey-add -f {{ pub_ssh_key }} --label {{ GUID }} 