---
- name: List ssh-keys available
# Should be changed to Ansible module
  command: >-
    ibmcloud sl security sshkey-list--output json
  register: r_sshkey_list

- name: Block to create sshkey file if it does not exist
  block:
  when: GUID not in r_sshkey_list.stdout

    - set_fact:
        pub_ssh_key: "{{ infra-ibm-ssh-key-pubssh-file }}"

    - name: Create pubssh file
      file:
        contents: "{{ infra-ibm-ssh-key-pubssh-key  }}"
        dest: "{{ pub_ssh_key }}"

    - name: Upload the ssh-keys
      command: >-
        ibmcloud sl security sshkey-add -f {{ pub_ssh_key }} --label {{ GUID }} 