################################################################################
################################################################################
### Environment Structure
################################################################################
################################################################################
## Environment Sizing

node_instance_type: cx2-2x4

node_instance_image: ibm-centos-7-6-minimal-amd64-2

# How many do you want for each instance type
node_instance_count: 1

# Environment Instances
instances:
  - name: "node"
    count: "{{ node_instance_count }}"
    unique: true
    public_dns: true
    dns_loadbalancer: false
    image: "{{ node_instance_image }}"
    flavor: "{{ node_instance_type }}"
    tags:
      - key: "AnsibleGroup"
        value: "bastions"
      - key: "ostype"
        value: "linux"
      - key: "instance_filter"
        value: "{{ env_type }}-{{ email }}"
    volumes:
      - name: '/dev/sda1'
        size: 20
    security_groups:
      - BastionSG

security_groups:
- name: bastion_sg
  description: Bastion security group allows basic icmp and SSH ingress and egress to *
  rules:
  - protocol: icmp
    direction: inbound
  - protocol: tcp
    direction: inbound
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - protocol: tcp
    direction: outbound

# Stuff that only GPTE cares about:
install_ipa_client: false

################################################################################
################################################################################
### Common Host settings
################################################################################
################################################################################

repo_method: satellite
# Do you want to run a full yum update
update_packages: true
common_packages:
  - python
  - unzip
  - bash-completion
  - tmux
  - wget
  - git
  - vim-enhanced
  - at

###V2WORK, these should just be set as default listed in the documentation
install_bastion: false
install_common: true
## SB Don't set software_to_deploy from here, always use extra vars (-e) or "none" will be used
#software_to_deploy: none


## guid is the deployment unique identifier, it will be appended to all tags,
## files and anything that identifies this environment from another.
# Using GUID is required, if it is not passed in the command line or uncommented
# here the deployment will fail
#guid: defaultguid



###V2WORK, these should just be set as default listed in the documentation
# This is where the ssh_config file will be created, this file is used to
# define the communication method to all the hosts in the deployment
deploy_local_ssh_config_location: "{{output_dir}}/"


### If you want a Key Pair name created and injected into the hosts,
# set `set_env_authorized_key` to true and set the keyname in `env_authorized_key`
# you can use the key used to create the environment or use your own self generated key
# if you set "use_own_key" to false your PRIVATE key will be copied to the bastion. (This is {{key_name}})

###V2WORK, these should just be set as default listed in the documentation
use_own_key: false
env_authorized_key: "{{guid}}key"
set_env_authorized_key: true

###V2WORK THIS SHOULD MOVE INTO THE ROLE
# This var is used to identify stack (cloudformation, azure resourcegroup, ...)
project_tag: "{{ env_type }}-{{ guid }}"
