- name: Step 000 Pre Infrastructure
  hosts: localhost
  gather_facts: false
  become: false
  tags:
    - step001
    - pre_infrastructure
    - generate_env_keys
  tasks:
    - debug:
        msg: "Step 000 Pre Infrastructure"

    - import_role:
        name: infra-local-create-ssh_key
      when: set_env_authorized_key | bool
