---
- name: Step 003 Pre Software
  hosts: localhost
  gather_facts: false
  become: false
  tasks:
    - debug:
        msg: "Step 003 Pre Software"
    - import_role:
        name: infra-local-create-ssh_key
      when: set_env_authorized_key | bool
    - name: Setup strong passwords
      set_fact:
        strong_login_password: "{{ lookup('password', '/dev/null length=12 chars=ascii_letters,digits') }}"
    - name: Setup strong passwords
      set_fact:
        student_password: "{{ strong_login_password }}"
        vscode_user_password: "{{ strong_login_password }}"

- name: Configure all hosts with Repositories
  hosts: all:!satellites
  become: true
  tags:
    - step004
    - common_tasks
  roles:
    - { role: "set-repositories", when: 'repo_method is defined' }

- name: Configure all hosts with Repositories
  hosts: all
  become: true
  tags:
    - step004
    - common_tasks
  roles:
    - { role: "set_env_authorized_key", when: 'set_env_authorized_key | bool' }

- name: Configuring Bastion Hosts
  hosts: bastions 
  become: true
  tags:
    - step004
    - bastion_tasks

  pre_tasks:
    - name: Strong password brought from localhost 
      set_fact: 
        student_password: "{{ hostvars['localhost']['student_password'] }}"
        vscode_user_password: "{{ hostvars['localhost']['vscode_user_password'] }}"
  
  roles:
    - { role: "common", when: 'install_common | default(true) | bool' }
    - { role: "bastion", when: 'install_bastion | default(true) |bool' }
    - { role: "bastion-student-user", when: 'install_student_user | default(true) | bool' }
    - { role: "control-user", when: 'install_control_user | default(true) | bool' }
    - { role: "vscode-server", when: 'install_vscode_server | default(true) | bool' }

- name: Clean up for satellite node
  hosts: satellites
  become: true
  tags:
    - satellite_cleanup
  tasks:
    - name: Create selinux autorelabel file
      file:
        path: /.autorelabel
        state: touch
    
    - name: Replace private ip in /etc/hosts
      replace:
        path: /etc/hosts
        regexp: "^.*satellite.example.com$"
        # replace: "192.168.50.163 satellite.example.com"
        replace: "{{ private_ip_address }} satellite.example.com"


- name: PreSoftware flight-check
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tags:
    - flight_check
  tasks:
    - debug:
        msg: "Pre-Software checks completed successfully"
