---
- name: Get a list of workspaces
  command: >
    ibmcloud schematics workspace list -o json
  register: r_workspace_list

- name: Check if workspace already exists
  set_fact:
    workspace_exists: false

- name: Check if workspace already exists
  when: r_workspace_list.workspaces | json_query(workspace_query) | length > 0
  set_fact:
    workspace_exists: true
  vars:
    workspace_query: >
      [?name=={{ GUID }}-workspace]

- name: Set the workspace ID if it exists
  when: workspace_exists
  set_fact:
    workspace_id: r_workspace_list.workspaces | json_query(workspace_id_query)
  vars:
    workspace_id_query: >
      [?name=='guid-workspace'].id|[0]

- name: Generate a RG list
  command: >-
    ibmcloud resource groups -o json 
  register: r_rg_list

- name: Create Resource Group
  when: "{{ GUID }}-rg not in r_rg_list.stdout"
  command: >-
    ibmcloud resource group-create {{ GUID }}-rg --output json

- name: Create the workspace
  when: not workplace_exists
  command: >
    ibmcloud schematics workspace new --file {{ ibm_cloud_workspace_config }} -o json
  register: r_workspace

- name: Update the workspace
  when: workplace_exists
  command: >
    ibmcloud schematics workspace update --id {{ workspace_id }}

