---
- name: Get a list of workspaces
  uri:
    url: https://us.schematics.cloud.ibm.com/v1/workspaces
    method: GET
    headers:
      Authorization: Bearer {{ infra_ibm_workspace_create_access_token }}
  register: r_workspaces
  tags: testing

- name: Create workspace if it does not exist
  when: r_workspaces.json.workspaces | json_query(workspace_query) | length == 0
  uri:
    url: https://us.schematics.cloud.ibm.com/v1/workspaces
    method: POST
    body_format: json
    status_code: 201
    headers:
      Authorization: Bearer {{ infra_ibm_workspace_create_access_token }}
    body: "{{ lookup('file', ibm_cloud_workspace_config) }}"
  vars:
    workspace_query: >
      [?name=='{{ guid }}-workspace']
  register: r_new_workspace
  tags: testing
  
- name: Get a list of workspaces
  uri:
    url: https://us.schematics.cloud.ibm.com/v1/workspaces
    method: GET
    headers:
      Authorization: Bearer {{ infra_ibm_workspace_create_access_token }}
  register: r_workspaces
  tags: testing

- name: Get the workspace ID
  set_fact:
    workspace_id: "{{ r_workspaces.json.workspaces | json_query(workspace_query) }}"
  vars:
    workspace_query: >
      [?name=='{{ guid }}-workspace'].id|[0]

- debug:
    var: workspace_id
