---
- name: Set the location for storing the workspace config
  set_fact:
    ibm_cloud_workspace_config: "{{output_dir}}/{{ env_type }}.{{ guid }}.{{cloud_provider}}_workspace.json"

- name: Generate the workspace config from template
  template:
    src: workspace-template.json.j2
    dest: "{{ ibm_cloud_workspace_config }}"

- name: Stop if debugging template
  when: debug_template | default(false) | bool
  fail:
    msg: "Check template here: {{ ibm_cloud_workspace_config }}"

- name: Validate workspace config
  assert:
    that: >
      lookup('file', ibm_cloud_workspace_config) | from_json is succeeded
    success_msg: Workspace config is syntactically valid