---
- name: Getting the resource-group list
  command: >-
    ibmcloud resource groups
  register: r_rglist

- name: Create the resource group if not exist.
  command: >- 
    ibmcloud resource group-create "{{ GUID }}-rg"
  when: "{{ GUID }}-rg not in r_rglist.stdout"