---
- name: Get the resource group list
  uri:
    url: https://resource-controller.cloud.ibm.com/v2/resource_groups?account_id={{ infra_ibm_prep_account_id }}
    method: GET
    headers:
      Authorization: Bearer {{ infra_ibm_prep_access_token }}
  register: r_rg_list
  tags: testing

- debug:
    var: r_rg_list
  tags: testing

- name: Create resource group if it does not exist
  when: r_rg_list.json.resources | json_query(rg_query) | length == 0
  uri:
    url: https://resource-controller.cloud.ibm.com/v2/resource_groups
    method: POST
    body_format: json
    status_code: 201
    headers:
      Authorization: Bearer {{ ibm_access_token }}
    body:
      name: "{{ guid }}-rg"
      account_id: "{{ ibm_account_id }}"
  vars:
    rg_query: >
      [?name=='{{ guid }}-rg']
  tags: testing

- name: Get the resource group list
  uri:
    url: https://resource-controller.cloud.ibm.com/v2/resource_groups?account_id={{ infra_ibm_prep_account_id }}
    method: GET
    headers:
      Authorization: Bearer {{ infra_ibm_prep_access_token }}
  register: r_rg_list
  tags: testing

- debug:
    var: r_rg_list
  tags: testing

- name: Set fact for resource group ID
  set_fact:
    resource_group_id: "{{ r_rg_list.json.resources | json_query(rg_query) }}"
  vars:
    rg_query: >
      [?name=='{{ guid }}-rg'].id|[0]
  tags: testing
