---
- name: Delete resource group
  command: >
    ibmcloud resource group-delete {{ guid }}-rg -f

- name: Verify resource group is deleted
  command: >
    ibmcloud resource groups --output json
  register: r_resource_groups
  retries: 10
  delay: 10
  until: (r_resource_groups.stdout | from_json) | json_query(rg_present_query) | length == 0
  vars:
    rg_present_query: >
      [?name=='{{ guid }}-rg']