---
- name: Destroy workspace
  command: >
    ibmcloud schematics workspace delete --id {{ workspace_id }} --force

- name: Wait for workspace to be deleted
  command: >
    ibmcloud schematics workspace list -o json
  register: r_updated_workspaces
  retries: 20
  delay: 30
  until: (r_updated_workspaces.stdout | from_json).workspaces | json_query(deleted_workspace_query) | length == 0
  vars:
    deleted_workspace_query: >
      [?name=='{{ guid }}-workspace']
