---
- name: Listing ssh-key
  command: >
    ibmcloud is keys --json
  register: r_ssh_keys

- name: Set the key_pair_id 
  set_fact:
    key_pair_id: "{{ (r_ssh_keys.stdout | from_json) | json_query(key_pair_id_query) }}"
  vars:
    key_pair_id_query: >
      [?name=='{{ guid }}-key'].id|[0]

- name: Delete key pair
  command: >
    ibmcloud is key-delete {{ key_pair_id }} --force 
