---
- name: Get information about the workspace
  command: >
    ibmcloud schematics workspace get --id {{ workspace_id }} -o json
  register: r_full_workspace

- name: Set workspace template ID
  set_fact:
    workspace_template_id: "{{ (r_full_workspace.stdout | from_json).template_data[0].id }}"
- debug:
    var: workspace_template_id
  
- name: Upload TF tarball to workspace
  command: >
    ibmcloud schematics workspace upload --id {{ workspace_id }}
    --file {{ ibm_cloud_template_tar }} --template {{ workspace_template_id }}
