---
# TODO Use ansible modules
# TODO Use json_query
- name: Getting the resource-group list
  command: >-
    ibmcloud resource groups
  register: r_rglist

- name: Create the resource group if not exist.
  command: >- 
    "ibmcloud resource group-create {{ GUID }}"
  when: GUID not in r_rglist.stdout