---
# TODO Use ansible modules
# TODO Use json_query
- name: Getting the resource-group list
  command: >-
    ibmcloud resource groups --output json
  register: r_rg_list

- debug:
    var: r_rg_list.stdout | from_json

- name: Check if resource group already exists
  set_fact:
    resource_group_exists: false

- name: Check if resource group already exists
  when: (r_rg_list.stdout | from_json) | json_query(rg_query) | length > 0
  set_fact:
    resource_group_exists: true
  vars:
    rg_query: >
      [?name=='{{ guid }}-rg']

- debug:
    var: resource_group_exists

- name: Get the ID of resource group if it exists
  when: resource_group_exists
  set_fact:
    resource_group_id: "{{ (r_rg_list.stdout | from_json) | json_query(rg_id_query) }}"
  vars:
    rg_id_query: >
      [?name=='{{ guid }}-rg'].id|[0]

- name: Create the resource group if it does not exist
  when: not resource_group_exists
  block:
  - name: Create the resource group
    command: >
      ibmcloud resource group-create {{ guid }}-rg --output json
    register: r_rg_new

  - name: Get ID of new resource group
    set_fact:
      resource_group_id: "{{ (r_rg_new.stdout | from_json).id }}"
