---

# sample vars configuration file
env_type: ansible-advanced-v2    # Name of config to deploy
output_dir: /tmp/output_dir             # Writable working scratch directory
email: name@example.com                 # User info for notifications
guid: guid01                            # Your Global UNIQUE Identifier
cloud_provider: osp                     # Which AgnosticD Cloud Provider to use


# Control user settings
control_user_name: devops
control_user_resource_dir_name: materials
control_user_ssh_config: ./files/ssh_config.j2
control_user_directories:
  - ".config/openstack"
  
control_user_copy_user_templates:
  - template: ./files/clouds.yaml.j2
    resource: clouds.yaml
    home: .config/openstack/clouds.yaml

  - template: ./files/gitconfig.j2
    home: .gitconfig

# Gitlab server public name for configuration
gitlab_server_public_hostname: "{{ groups['utilities'][0] | regex_replace('\\..*$') }}.{{ guid }}.{{ osp_cluster_dns_zone }}"

gitlab_server_groups:
  - ansible
gitlab_server_users:
  - name: "{{ control_user_name }}"
    username: "{{ control_user_name }}"
    password: "{{ student_password }}"
    email: "{{ control_user_name }}@{{ gitlab_server_public_hostname }}"
    sshkey_name: sshkey
    sshkey_file: "{{ output_dir }}/{{ env_authorized_key }}.pub"
    group: ansible
    access_level: maintainer

gitlab_server_projects:
  - name: gitops-lab
    group: ansible
    import_url: https://github.com/redhat-gpte-devopsautomation/gitops-lab.git


### VScoder server variables
vscode_user_name: "{{ control_user_name }}"
vscode_server_hostname: "{{ groups['bastions'][0] | regex_replace('\\..*$') }}.{{ guid }}.{{ osp_cluster_dns_zone }}"

###Satellite variables
#repo_method: satellite
#rhel_repos:
#  - rhel-7-server-rpms
#  - rhel-7-server-rh-common-rpms
#  - rhel-7-server-extras-rpms
#  - rhel-7-server-optional-rpms
#  - rhel-server-rhscl-7-rpms
#  - rhel-7-server-ansible-2.9-rpms
...
