--- 
- name: Create jupyterhub instance
  k8s:
    state: present    
    definition: "{{ lookup('file', 'jupyterhub_kfdef.yaml' ) | from_yaml }}"

- name: "Wait for jupyterhub pod to be in Ready state"
  k8s_info:
    kind: Pod
    label_selectors:
      - app = jupyterhub
    namespace: labs-infra
  register: r_pod_status
  until: (r_pod_status | json_query("resources[0].status.containerStatuses[0].ready") | bool) == true
  retries: 80
  delay: 10

