---
- name: List SSH keys available in account
  command: >
    ibmcloud is keys --json
  register: r_ssh_keys

- debug:
    var: r_ssh_keys.stdout | from_json

- name: Verify SSH key does not already exist
  shell: >-
    cat ssh-rsa {{output_dir}}/{{env_authorized_key}}.pub
    | ssh-keygen -lf - 
    | cut -d " " -f2
  register: r_ssh_key_fingerprint

- name: Create SSH key using infra key
  when: (r_ssh_keys.stdout | from_json) | json_query(ssh_key_query) | length == 0
  command: >-
    ibmcloud is keyc {{ guid }}-key @{{output_dir}}/{{env_authorized_key}}.pub
    --resource-group-id {{ resource_group_id }} --json
  register: r_ssh_key_new
  vars:
    ssh_key_query: >
      [?fingerprint=='{{ r_ssh_key_fingerprint.stdout }}']

# - name: Create SSH key if it does not exist
#   when: (r_ssh_keys.stdout | from_json) | json_query(ssh_key_query) | length == 0
#   command: >-
#     ibmcloud is keyc {{ guid }}-key "{{ infra_ibm_ssh_key_pubssh_key }}"
#     --resource-group-id {{ resource_group_id }} --json
#   vars:
#     ssh_key_query: >
#       [?name=='{{ guid }}-key']
#   register: r_ssh_key_new
#   tags:
#     - ssh_keys

# TODO: Add task to get SSH key ID for other use