---
- import_playbook: ../include_vars.yml

- name: Delete Infrastructure
  hosts: localhost
  connection: local
  gather_facts: False
  become: no
  tasks:
  - name: Destroy workspace and resources
    import_role:
      name: infra-ibm-destroy