---
- name: Step 001.1 Deploy Infrastructure
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tags:
    - step001
    - step001.1
    - deploy_infrastructure
  tasks:
  - name: Get bearer token
    uri:
      url: https://iam.cloud.ibm.com/identity/token
      method: POST
      body_format: form-urlencoded
      body: "grant_type=urn%3Aibm%3Aparams%3Aoauth%3Agrant-type%3Aapikey&apikey={{ ibm_admin_api_key }}"
    register: r_token
    tags: testing

  - name: Set fact for bearer token
    set_fact:
      ibm_access_token: "{{ r_token.json.access_token }}"
    tags: testing

  - name: Create resource group and pre-reqs
    import_role:
      name: infra-ibm-prep

  # This may be added in if this ends up being supported
  # - name: Setting quotas
  #   import_role: infra-ibm-setting-quotas
      
  - name: Create Workspace
    import_role:
      name: infra-ibm-workspace-create

  - name: Create Terraform config
    import_role:
      name: infra-ibm-template-create