---
- name: Step 001.1 Deploy Infrastructure
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tags:
    - step001
    - step001.1
    - deploy_infrastructure
#  collections:
#  - ibm.cloudcollection
  tasks:
  - name: ssh-key upload process
    import_role: infra-ibm-ssh-key

  - name: Create resource group
    import_role: infra-ibm-rg-create

  - name: Setting quotas.
    import_role: infra-ibm-setting-quotas
      
  - name: Create Workspace
    import_role: infra-ibm-workspace-create

  - name: Generate Terraform config
    # import_role: infra-ibm-template-generate

  - name: Apply Terraform config
    # import_role: infra-ibm-template-create