---
- name: Step 001.1 Deploy Infrastructure
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tags:
    - step001
    - step001.1
    - deploy_infrastructure
  collections:
  - ibm.cloudcollection
  tasks:
    - name: Upload ssh-key to the specified region
      import_role: infra-ibm-sshkey-upload

    - name: Create Schematics resources and dependencies
      import_role: infra-ibm-workspace-create

    - name: Generate Terraform plan
      import_role: infra-ibm-terraform-plan

    - name: Terraform Apply
      import_role: infra-ibm-terraform-apply