---
- name: Step 001.1 Deploy Infrastructure
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tags:
    - step001
    - step001.1
    - deploy_infrastructure
  collections:
  - ibm.cloudcollection
  tasks:
  - name: Create resource group and pre-reqs
    import_role:
      name: infra-ibm-prep-create

  # This may be added in if this ends up being supported
  # - name: Setting quotas
  #   import_role: infra-ibm-setting-quotas
      
  - name: Create Workspace
    import_role:
      name: infra-ibm-workspace-create

  - name: Create Terraform config
    import_role:
      name: infra-ibm-template-create